require("ponson.plugins-setup")
require("ponson.core.options")
require("ponson.core.keymaps")
require("ponson.core.colorscheme")
require("ponson.plugins.comment")
require("ponson.plugins.nvim-tree")
require("ponson.plugins.lualine")
require("ponson.plugins.telescope")
require("ponson.plugins.nvim-cmp")
require("ponson.plugins.lsp.mason")
require("ponson.plugins.lsp.lspsaga")
require("ponson.plugins.lsp.lspconfig")
require("ponson.plugins.lsp.null-ls")
require("ponson.plugins.autopairs")
require("ponson.plugins.treesitter")
require("ponson.plugins.gitsigns")

